import 'package:flutter_test/flutter_test.dart';
import 'package:trackmytrip/core/services/trip_share_service.dart';
import 'package:trackmytrip/models/expense.dart';
import 'package:trackmytrip/models/stoppage.dart';
import 'package:trackmytrip/models/trip.dart';
import 'package:trackmytrip/models/trip_member.dart';
import 'package:trackmytrip/models/trip_audit_log.dart';

void main() {
  group('Sprint 14: Loops 116–120 Memories, Audit Hub & Centennial Gate II Tests', () {
    final trip = Trip(
      id: 'trip-markdown-1',
      title: 'Himalayan Expedition',
      createdByMemberId: 'm1',
      createdAt: DateTime(2026, 10, 1),
      startDate: DateTime(2026, 10, 1),
      endDate: DateTime(2026, 10, 7),
      defaultCurrency: 'INR',
      members: const [
        TripMember(id: 'm1', name: 'Arun', email: 'arun@example.com'),
        TripMember(id: 'm2', name: 'Bob', email: 'bob@example.com'),
      ],
    );

    final stoppages = [
      Stoppage(
        id: 'stop-base',
        tripId: 'trip-markdown-1',
        name: 'Basecamp Cafe',
        latitude: 31.1048,
        longitude: 77.1734,
        category: 'Food',
        arrivedAt: DateTime(2026, 10, 1, 10, 0),
        departedAt: DateTime(2026, 10, 1, 12, 0),
        address: 'Old Manali, Himachal Pradesh',
        notes: 'Great ginger tea before trek',
        createdBy: 'm1',
      ),
    ];

    final expenses = <Expense>[
      Expense(
        id: 'exp-1',
        tripId: 'trip-markdown-1',
        title: 'Trek Gear Rental',
        totalAmount: 1800.0,
        currency: 'INR',
        paidByMemberId: 'm1',
        category: 'Activity',
        splitType: SplitType.equal,
        createdAt: DateTime(2026, 10, 1, 11, 0),
        splits: const [],
      ),
    ];

    final package = TripPackage(
      trip: trip,
      stoppages: stoppages,
      expenses: expenses,
      memories: const [],
      settlements: const [],
    );

    test('Loop 117: Batch Album Summary formatting generates valid entries', () {
      final summary = StringBuffer()
        ..writeln('📸 ${trip.title} - Photo Album (1 Memories)')
        ..writeln('----------------------------------------')
        ..writeln('• ${stoppages.first.name} - "Summit view" (01 Oct)')
        ..writeln('----------------------------------------');

      final text = summary.toString();
      expect(text, contains('Himalayan Expedition'));
      expect(text, contains('Basecamp Cafe'));
      expect(text, contains('Summit view'));
    });

    test('Loop 118: Audit Log filter by member matches member identifier correctly', () {
      final logs = [
        TripAuditLog(
          id: 'log-1',
          tripId: 'trip-markdown-1',
          actionType: 'add_expense',
          itemTitle: 'Lunch',
          performedByMemberId: 'm1',
          performedByName: 'Arun',
          timestamp: DateTime(2026, 10, 1),
        ),
        TripAuditLog(
          id: 'log-2',
          tripId: 'trip-markdown-1',
          actionType: 'add_expense',
          itemTitle: 'Dinner',
          performedByMemberId: 'm2',
          performedByName: 'Bob',
          timestamp: DateTime(2026, 10, 1),
        ),
      ];

      final arunLogs = logs.where((l) => l.performedByMemberId == 'm1').toList();
      final bobLogs = logs.where((l) => l.performedByMemberId == 'm2').toList();

      expect(arunLogs.length, 1);
      expect(arunLogs.first.itemTitle, 'Lunch');
      expect(bobLogs.length, 1);
      expect(bobLogs.first.itemTitle, 'Dinner');
    });

    test('Loop 119: Markdown Itinerary Export produces valid GitHub-flavored markdown structure', () {
      final md = TripShareService.generateMarkdownItinerary(package);

      expect(md, contains('# 🗺️ Himalayan Expedition'));
      expect(md, contains('**Travelers:** Arun, Bob'));
      expect(md, contains('## 📍 Stoppages & Itinerary'));
      expect(md, contains('### 1. Basecamp Cafe (Food)'));
      expect(md, contains('- **Location:** Old Manali, Himachal Pradesh'));
      expect(md, contains('- **Notes:** Great ginger tea before trek'));
      expect(md, contains('## 💰 Financial Breakdown'));
      expect(md, contains('| Date | Title | Category | Paid By | Amount |'));
      expect(md, contains('Trek Gear Rental'));
      expect(md, contains('*Generated by TrackMyTrip*'));
    });

    test('Loop 120: Centennial Gate II master verification across sprint models', () {
      expect(package.trip.id, 'trip-markdown-1');
      expect(package.stoppages.length, 1);
      expect(package.expenses.length, 1);
      expect(package.expenses.first.totalAmount, 1800.0);
    });
  });
}
