# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - avoid_unnecessary_containers
    - unnecessary_parenthesis
    - unnecessary_string_interpolations
    - unnecessary_nullable_for_final_variable_declarations
    - no_duplicate_case_values

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
