// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9koYl1tSUH3XB4hVq9MG5Yz-Rmg-QdUc',
    appId: '1:731719697818:web:7765ef639c831331bce623',
    messagingSenderId: '731719697818',
    projectId: 'trackmytrip-sync-2026',
    authDomain: 'trackmytrip-sync-2026.firebaseapp.com',
    storageBucket: 'trackmytrip-sync-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3xg07jKRC-jDcfKCXBLC5-EMCzz4VRgc',
    appId: '1:731719697818:android:fbf3b3bfba7fa282bce623',
    messagingSenderId: '731719697818',
    projectId: 'trackmytrip-sync-2026',
    storageBucket: 'trackmytrip-sync-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYF_y9I8jnWH3jQOn-7lER5LRK7Bx1Es',
    appId: '1:731719697818:ios:c695ae0f15590c96bce623',
    messagingSenderId: '731719697818',
    projectId: 'trackmytrip-sync-2026',
    storageBucket: 'trackmytrip-sync-2026.firebasestorage.app',
    iosBundleId: 'com.triptracker.tripTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxYF_y9I8jnWH3jQOn-7lER5LRK7Bx1Es',
    appId: '1:731719697818:ios:c695ae0f15590c96bce623',
    messagingSenderId: '731719697818',
    projectId: 'trackmytrip-sync-2026',
    storageBucket: 'trackmytrip-sync-2026.firebasestorage.app',
    iosBundleId: 'com.triptracker.tripTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9koYl1tSUH3XB4hVq9MG5Yz-Rmg-QdUc',
    appId: '1:731719697818:web:c120290b67859c5bbce623',
    messagingSenderId: '731719697818',
    projectId: 'trackmytrip-sync-2026',
    authDomain: 'trackmytrip-sync-2026.firebaseapp.com',
    storageBucket: 'trackmytrip-sync-2026.firebasestorage.app',
  );
}
